version: "3"

services:
  webapp:
    build:
      dockerfile: "./Dockerfile"
      context: "."
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/app
    networks:
      - app-network

  nginx:
    image: "nginx:latest"
    depends_on:
      - webapp
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      start_period: 0s
      interval: 5s
      timeout: 3s
      retries: 2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
