version: "3"

services:
  webapp:
    build:
      dockerfile: "./Dockerfile"
      context: "."
    depends_on:
      - nginx
      - mysql
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./server.js:/src/server.js
    networks:
      - app-network

  nginx:
    image: "nginx:latest"
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
